# Generated by Django 6.0.7 on 2026-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='gps_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
